# Site settings
title: PHPSC Conference 2019
email: coordenadores@phpsc.com.br
description: > # this means to ignore newlines until "baseurl:"
  Hotsite para a PHPSC Conference 2019
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://conf.phpsc.com.br" # the base hostname & protocol for your site

twitter_username: php_sc
github_username: phpsc
facebook_username: santa.catarina.elephants

sponsors_bronze:
  - url: "https://www.umbler.com/br?utm_source=phpsc&utm_medium=phpscconference2018&utm_campaign=phpscconference2018"
    name: "Umbler"
    image: "img/sponsors/umbler.png"
    text: "Hospedagem Cloud por demanda para Agências e Devs"
  - url: "https://www.socialbase.com.br/br?utm_source=phpsc&utm_medium=phpscconference2018&utm_campaign=phpscconference2018"
    name: "SocialBase"
    image: "img/sponsors/socialbase.png"
    text: "Rede Social Corporativa: Comunicação e Colaboração"

supporters:
- - url: "http://www.unisul.br/wps/portal/home/ensino/graduacao/sistemas-de-informacao?utm_source=phpsc&utm_medium=phpscconference2018&utm_campaign=phpscconference2018#?unidade=28"
    name: "Unisul"
    image: "img/supporters/unisul.png"
    text: "Curso de Sistemas de Informação Florianópolis"
  - url: "https://www.hostinger.com.br/?utm_source=phpsc&utm_medium=phpscconference2018&utm_campaign=phpscconference2018"
    name: "Hostinger"
    image: "img/supporters/hostinger.jpg"
    text: "A hospedagem de sites mais rápida do mercado, por um preço imbatível!"
  - url: "https://www.geekhunter.com.br/?utm_source=phpsc&utm_medium=phpscconference2018&utm_campaign=phpscconference2018"
    name: "GeekHunter"
    image: "img/supporters/geekhunter.png"
    text: "Conectamos os melhores desenvolvedores às empresas mais desejadas!"
  - url: "https://king.host/?utm_source=phpsc&utm_medium=phpscconference2018&utm_campaign=phpscconference2018"
    name: "KingHost"
    image: "img/supporters/kinghost.png"
    text: "Hospedagem de Site com Uptime de 99.9%"
- - url: "https://www.jetbrains.com/?utm_source=phpsc&utm_medium=phpscconference2018&utm_campaign=phpscconference2018"
    name: "JetBrains"
    image: "img/supporters/jetbrains.png"
    text: "Developer Tools for Professionals and Teams"

talks:
 - time_start: "08:15"
   time_end: "09:00"
   title: "Credenciamento e recepção dos participantes"
   speaker: ""
   description: "Todas as pessoas inscritas e palestrantes devem retirar seus crachás e kit de publicidade nos balcões de credenciamento (localizados na entrada do evento) para obterem acesso ao auditório."
   keynote: false
 - time_start: "09:00"
   time_end: "09:15"
   title: "Abertura"
   speaker: ""
   description: "No auditório, os participantes recebem as boas vindas por parte dos realizadores e patrocinadores. Na abertura, todos serão orientados sobre o funcionamento do evento, destaques e outras informações."
   keynote: false
 - time_start: "12:15"
   time_end: "13:15"
   title: "Almoço"
   speaker: ""
   description: "Uma excelente oportunidade para os participantes, as empresas patrocinadoras e apoiadoras, os palestrantes e os coordenadores interagirem e trocarem ideias."
   keynote: false
 - time_start: "17:45"
   time_end: "18:00"
   title: "Encerramento e Sorteios"
   speaker: ""
   description: "No encerramento, ocorrem os sorteios dos brindes oferecidos pelas empresas apoiadoras e patrocinadoras."
   keynote: false
 - time_start: "18:00"
   time_end: "19:15"
   title: "Deslocamento até o PHPPub"
   speaker: ""
   description: "Parte dos organizadores vai se dirigir para um bar da região."
   keynote: false
 - time_start: "19:15"
   time_end: "22:00"
   title: "PHPPub = 🐘 + 🍻"
   speaker: ""
   description: "Vamos relaxar, tomar umas cervejas e curtir o fim do dia. Todos são convidados para este momento de descontração e networking!"
   keynote: false

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "img/portfolio"
    values:
      image: true
