# Site settings
title: PHPSC Conference 2018
email: thiagopaes@phpsc.com.br
description: > # this means to ignore newlines until "baseurl:"
  Hotsite para a PHPSC Conference 2018
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://conf.phpsc.com.br" # the base hostname & protocol for your site

twitter_username: php_sc
github_username: phpsc
facebook_username: santa.catarina.elephants

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "img/portifolio"
    values:
      image: true