# Site settings
title: PHPSC Conference 2018
email: coordenadores@phpsc.com.br
description: > # this means to ignore newlines until "baseurl:"
  Hotsite para a PHPSC Conference 2018
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://conf.phpsc.com.br" # the base hostname & protocol for your site

twitter_username: php_sc
github_username: phpsc
facebook_username: santa.catarina.elephants

sponsors_bronze:
  - url: "https://www.umbler.com/br?utm_source=phpsc&utm_medium=phpscconference2018&utm_campaign=phpscconference2018"
    name: "Umbler"
    image: "img/sponsors/umbler.png"
    text: "Hospedagem Cloud por demanda para Agências e Devs"

supporters:
  - url: "http://www.unisul.br/wps/portal/home/ensino/graduacao/sistemas-de-informacao?utm_source=phpsc&utm_medium=phpscconference2018&utm_campaign=phpscconference2018#?unidade=28"
    name: "Unisul"
    image: "img/supporters/unisul.png"
    text: "Curso de Sistemas de Informação Florianópolis"
  - url: "https://www.hostinger.com.br/?utm_source=phpsc&utm_medium=phpscconference2018&utm_campaign=phpscconference2018"
    name: "Hostinger"
    image: "img/supporters/hostinger.jpg"
    text: "A hospedagem de sites mais rápida do mercado, por um preço imbatível!"
  - url: "https://www.geekhunter.com.br/?utm_source=phpsc&utm_medium=phpscconference2018&utm_campaign=phpscconference2018"
    name: "GeekHunter"
    image: "img/supporters/geekhunter.png"
    text: "Conectamos os melhores desenvolvedores às empresas mais desejadas!"

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "img/portfolio"
    values:
      image: true
